### ISSUE TITLE
googleStorageBucket a requirement even for command-line usage?

### ISSUE THREAD

**Issue by larsschwarz** [google-pay/pass-converter#7]
According to the docs

> When running as a command-line tool, you can convert passes to Google Wallet JWT payloads without any external dependencies.

but when running it via the command-line this is returned

`Cannot determine public host for images, googleStorageBucket config must be defined`

Does it mean that a Google Storage Bucket is a requirement? Can't seem to find an option that saves images locally instead?

**Comment by stephenmcd** [comment]
Hi Lars, thanks for raising this.

I made a change in a5673888405b710d6c4a29ad32fe76a79c479d79 that warns in this case instead of failing, so the docs can remain true, as you pointed out there is a contradiction there.

Note the warning it shows now - the resulting pass won't be saveable to Google Wallet as the passes require any images (and typically there is at least one required) to be publicly accessible, so you would need to edit the resulting JSON to add the full URL separately.
